version: '3.8'
services:
  cucumber-bot:
    image: coominpickle/cucumber:latest
    container_name: cucumber-discord-bot
    environment:
      - BOT_TOKEN=${BOT_TOKEN}                   # Bot token from dev portal
      - APPLICATION_ID=${APPLICATION_ID}         # Application ID from dev portal
      - INSTAGRAM_USERNAME=${INSTAGRAM_USERNAME} # Instagram username (for photo fallback)
      - INSTAGRAM_PASSWORD=${INSTAGRAM_PASSWORD} # Instagram password (for photo fallback)
      # Disable cogs by setting them to false, e.g.:
      # - INSTAGRAM_COG=false
      # - QUOTE_COG=false
    volumes:
      - ./config:/app/config
    restart: unless-stopped
