services:
  cucumber-bot:
    build:
      context: .
    image: coominpickle/cucumber:latest
    container_name: cucumber-discord-bot
    environment:
      - BOT_TOKEN=${BOT_TOKEN}  #Bot token from dev portal
      - APPLICATION_ID=${APPLICATION_ID}  #Application ID	from dev portal
      - INSTAGRAM_USERNAME=${INSTAGRAM_USERNAME}
      - INSTAGRAM_PASSWORD=${INSTAGRAM_PASSWORD}
      - SPOTIFY_CLIENT_ID=${SPOTIFY_CLIENT_ID}
      - SPOTIFY_CLIENT_SECRET=${SPOTIFY_CLIENT_SECRET}
      # Optional cog switches, e.g.:
      # INSTAGRAM_COG: "false"
      # QUOTE_COG: "false"
    volumes:
      - ./config:/app/config
    restart: unless-stopped

  bgutil-provider:
    image: brainicism/bgutil-ytdlp-pot-provider:1.3.1
    container_name: bgutil-provider
    restart: unless-stopped
