# .github/workflows/docker-image.yml

name: Build and push Docker image

on:
  push:
    branches:
      - master  # This specifies that the action will run on pushes to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Updated to the latest version for improved functionality

      - name: Set up Docker Buildx
<<<<<<< HEAD
        uses: docker/setup-buildx-action@v2  # Updated to the latest version for improved support with Buildx
=======
        uses: docker/setup-buildx-action@v1  # This sets up Docker Buildx, a Docker CLI plugin that extends the docker command with the full support of the features provided by Moby BuildKit builder toolkit
>>>>>>> parent of 16ab31b (Update docker-image.yml )

      - name: Log in to Docker Hub
        uses: docker/login-action@v2  # Updated to the latest version for improved Docker Hub login support
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # Use secrets for your Docker Hub username
          password: ${{ secrets.DOCKER_PASSWORD }}  # Use secrets for your Docker Hub password

<<<<<<< HEAD
      - name: Build Docker image
        run: |
          # Get the current timestamp for unique tagging
          TIMESTAMP=$(date +%s)

          # Build the Docker image and tag it with the timestamp
          docker build . --file Dockerfile --tag coominpickle/pixlet-push-update:$TIMESTAMP

          # Tag the same image with 'latest'
          docker tag coominpickle/pixlet-push-update:$TIMESTAMP coominpickle/pixlet-push-update:latest

      - name: Push Docker image to Docker Hub
        run: |
          # Push the image with the timestamp tag
          docker push coominpickle/pixlet-push-update:$TIMESTAMP
          
          # Push the 'latest' tag to Docker Hub
          docker push coominpickle/pixlet-push-update:latest
=======
      - name: Build and push Docker image
        uses: docker/build-push-action@v2  # This builds and pushes Docker images with Buildx
        with:
          push: true  # This ensures the image is pushed to Docker Hub
          tags: coominpickle/cucumber:latest  # Replace with your Docker Hub username and repository name
>>>>>>> parent of 16ab31b (Update docker-image.yml )
