name: Build and push Docker image

on:
  workflow_dispatch:
  push:
    branches:
      - main  # This specifies that the action will run on pushes to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # This checks out your repository under $GITHUB_WORKSPACE, so your workflow can access it

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1  # This sets up Docker Buildx, a Docker CLI plugin that extends the docker command with the full support of the features provided by Moby BuildKit builder toolkit

      - name: Log in to Docker Hub
        uses: docker/login-action@v1  # This logs into Docker Hub
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # Use secrets for your Docker Hub username
          password: ${{ secrets.DOCKER_PASSWORD }}  # Use secrets for your Docker Hub password

      - name: Build and push Docker image
        uses: docker/build-push-action@v2  # This builds and pushes Docker images with Buildx
        with:
          push: true  # This ensures the image is pushed to Docker Hub
          tags: coominpickle/cucumber:latest  # Replace with your Docker Hub username and repository name
