name: Build and push Docker image

on:
  push:
    branches:
      - master  # This specifies that the action will run on pushes to the main branch
  workflow_dispatch:  # This allows you to trigger the workflow manually

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # This checks out your repository under $GITHUB_WORKSPACE, so your workflow can access it

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1  # This sets up Docker Buildx, a Docker CLI plugin that extends the docker command with full support of the Moby BuildKit builder toolkit

      - name: Log in to Docker Hub
        uses: docker/login-action@v1  # This logs into Docker Hub
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # Use secrets for your Docker Hub username
          password: ${{ secrets.DOCKER_PASSWORD }}  # Use secrets for your Docker Hub password

      - name: Build Docker image
        run: |
          docker build . --file Dockerfile --tag coominpickle/pixlet-push-update:$(date +%s)  # Build image with a timestamp tag for uniqueness
          docker tag coominpickle/pixlet-push-update:$(date +%s) coominpickle/pixlet-push-update:latest  # Tag the image as 'latest'

      - name: Push Docker image to Docker Hub
        run: |
          docker push coominpickle/pixlet-push-update:$(date +%s)  # Push the timestamp tag first
          docker push coominpickle/pixlet-push-update:latest  # Push the 'latest' tag
