name: Build and push Docker image

on:
  push:
    branches:
      - master  # This specifies that the action will run on pushes to the main branch
  workflow_dispatch:  # This allows you to trigger the workflow manually

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Updated to the latest version for improved functionality

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2  # Updated to the latest version for improved support with Buildx

      - name: Log in to Docker Hub
        uses: docker/login-action@v2  # Updated to the latest version for improved Docker Hub login support
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # Use secrets for your Docker Hub username
          password: ${{ secrets.DOCKER_PASSWORD }}  # Use secrets for your Docker Hub password

      - name: Build Docker image
        run: |
          # Get the current timestamp for unique tagging
          TIMESTAMP=$(date +%s)

          # Build the Docker image and tag it with the timestamp
          docker build . --file Dockerfile --tag coominpickle/pixlet-push-update:$TIMESTAMP

          # Tag the same image with 'latest'
          docker tag coominpickle/pixlet-push-update:$TIMESTAMP coominpickle/pixlet-push-update:latest

      - name: Push Docker image to Docker Hub
        run: |
          # Push the image with the timestamp tag
          docker push coominpickle/pixlet-push-update:$TIMESTAMP
          
          # Push the 'latest' tag to Docker Hub
          docker push coominpickle/pixlet-push-update:latest
